### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by stefan1983** [pmarks-net/ipvfoo#39]
I would love to have ipvfoo as SAFARI Extension. Would be great if you could put this onto your roadmap.
 
Thanks

**Comment by pmarks-net** [comment]
I have no interest in this browser.

**Comment by A1bi** [comment]
I tried to port IPvFoo to Safari since it has recently introduced support for the WebExtensions API. Unfortunately the server IP address essential to IPvFoo is omitted from all web request event details. I can imagine that this is intended by Apple for whatever reason but I will open a bug report anyway.

**Comment by pmarks-net** [comment]
I recently got macOS Ventura running in KVM, and tried to build IPvFoo for Safari:

    % xcrun safari-web-extension-converter src

This is the resulting error:

- An extension with a non-persistent background page cannot listen to `webRequest` events.
- The `service_worker` script failed to load due to an error.

![Screenshot 2023-09-17 at 5 42 23 PM](https://github.com/pmarks-net/ipvfoo/assets/4578188/ae2d8b7e-706b-4c16-a06f-0924aac54162)

Using `firefox-manifest.json` with 'page_action' renamed to 'action', it gets far enough to render a ? and the popup, but `chrome.webRequest` is undefined.

Using the old `manifestv2` branch, I'm able to log `webRequest.onResponseStarted` events, but the `ip` field is missing.  So even when Safari adds support for webRequest in MV3, IPvFoo will be unimplementable unless they also start reporting IP addresses.

While writing this up, I noticed that A1bi already reached the same conclusion 2 years ago... at least I can report that nothing has changed since then.

**Comment by VCTGomes** [comment]
Any news about it?

**Comment by fabiohblage** [comment]
@pmarks-net, mudou de ideia sobre desenvolver para Safari essa semana extensão?

**Comment by pmarks-net** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest#browser_compatibility > onResponseStarted > details.ip > Safari = No

If that ever changes, I can start working on this.

**Comment by Fiyaas** [comment]
> မကြာသေးမီက ကျွန်ုပ်သည် KVM တွင်လည်ပတ်နေသော macOS Ventura ကိုရရှိထားပြီး Safari အတွက် IPvFoo ကိုတည်ဆောက်ရန်ကြိုးစားခဲ့သည်
> 
> ```
> % xcrun safari-web-extension-converter src
> ```
> 
> ဤသည်မှာ ရလဒ်အမှားဖြစ်သည်။
> 
> * မမြဲသော နောက်ခံစာမျက်နှာပါသော နောက်ဆက်တွဲတစ်ခုသည် `webRequest`အစီအစဉ်များကို နားမထောင်နိုင်ပါ။
> * `service_worker`အမှားအယွင်းတစ်ခုကြောင့် ဇာတ်ညွှန်းကို ဖွင့်၍မရပါ ။
> 
> ![Screenshot 2023-09-17 at 5 42 23 PM](https://github.com/pmarks-net/ipvfoo/assets/4578188/ae2d8b7e-706b-4c16-a06f-0924aac54162)
> 
> 'page_action' ကို 'action' သို့ အမည်ပြောင်း အသုံးပြုခြင်း `firefox-manifest.json`ဖြင့်၊ ၎င်းသည် render လုပ်ရန် လုံလောက်ပါသည်။ နှင့် ပေါ့ပ်အပ်၊ သို့သော် `chrome.webRequest`သတ်မှတ်မထားပါ။
> 
> ဌာနခွဲ ဟောင်းကို အသုံးပြု၍ ဖြစ်ရပ်များကို `manifestv2`မှတ်တမ်းတင်နိုင်သော်လည်း အကွက်ပျောက်နေသည်။ ထို့ကြောင့် Safari သည် MV3 တွင် webRequest အတွက် ပံ့ပိုးမှုကို ပေါင်းထည့်သောအခါတွင်ပင် IPvFoo သည် IP လိပ်စာများကို အစီရင်ခံခြင်းမှ စတင်ခြင်းမရှိပါက၊ IPvFoo သည် အကောင်အထည်ဖော်နိုင်မည်မဟုတ်ပေ။`webRequest.onResponseStarted``ip`
> 
> ဒါကိုရေးနေရင်းနဲ့ A1bi ဟာ လွန်ခဲ့တဲ့ 2 နှစ်က တူညီတဲ့ နိဂုံးချုပ်ကို ရောက်နေပြီဆိုတာ သတိပြုမိပါတယ်... အနည်းဆုံးတော့ အဲဒီကတည်းက ဘာမှ မပြောင်းလဲခဲ့ဘူးလို့ သတင်းပို့နိုင်ပါတယ်။

**Comment by Fiyaas** [comment]
> WebExtensions API အတွက် အထောက်အပံ့ကို မကြာသေးမီက မိတ်ဆက်ပေးခဲ့ပြီးဖြစ်သောကြောင့် IPvFoo ကို Safari `**[သို့](url)**` ပို့ရန် ကြိုးစားခဲ့သည်။ ကံမကောင်းစွာပဲ IPvFoo အတွက် မရှိမဖြစ်လိုအပ်သော ဆာဗာ IP လိပ်စာကို ဝဘ်တောင်းဆိုမှု[ဖြစ်ရပ်]([url]([url](url)))အသေးစိတ်များအားလုံးမှ ချန်လှပ်ထားသည်။ ဒါကို Apple က ဘာအကြောင်းကြောင့်ပဲ ရည်ရွယ်ထားတယ်ဆိုတာ ကျွန်တော် စိတ်ကူးကြည့်နိုင်ပေမယ့် ဘာပဲဖြစ်ဖြစ် bug အစီရင်ခံစာကို ဖွင့်ပါမယ်။

**Comment by Deafboy91** [comment]
@pmarks-net  

Hello, seem onResponseStarted > details.ip are now supported since Safari 18.4 (released on March 31). 
Can you check it out whenever that function working correctly?

Thanks

**Comment by agoodkind** [comment]
I had to shuffle around some files and throw together a few build scripts to get things easy enough to work with

**Comment by fabiohblage** [comment]
Muito obrigado, @pmarks-net , funcional no safari M2, 


<img width="422" height="599" alt="Image" src="https://github.com/user-attachments/assets/e82e23c5-59cf-4399-a1bb-83196b7fad75" />


<img width="1504" height="895" alt="Image" src="https://github.com/user-attachments/assets/8e58cc09-2e5b-46c2-9edc-bf111ba79400" />


<img width="1477" height="966" alt="Image" src="https://github.com/user-attachments/assets/5805c4a6-002a-4c6f-b652-46b29bdce0d5" />


<img width="1504" height="895" alt="Image" src="https://github.com/user-attachments/assets/a0a49520-d395-42a5-a187-f887dbacf775" />
